morador:
  topic:
    name: morador-mq
    
processo:
  topic:
    name: processo-mq

residencia:
  topic:
    name: residencia-mq
    
veiculo:
  topic:
    name: veiculo-mq
    
visita:
  topic:
    name: visita-mq
    
visitante:
  topic:
    name: visitante-mq
    
vinculos:
  topic:
    name: vinculo-mq
    
contribuicao:
  topic:
    name: contribuicao-mq
  